- alias: Svanhild thuis
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.svanhild_woonkamer
      above: 90
  action:
    service: notify.slack
    data_template:
      message: >
        Svanhild is thuis
      target: "@rob"
- alias: Svanhild weg
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.svanhild_woonkamer
      below: 10
  action:
    service: notify.slack
    data_template:
      message: >
        Svanhild is weg
      target: "@rob"

- id: mqtt_channel_check
  alias: Mqtt channel check
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: 'sensor.co2_woonkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.co2_slaapkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.co2_studeerkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.watermeter_lastupdate'
        above: 720
      - condition: numeric_state
        entity_id: 'sensor.ventilator_snelheid_lastupdate'
        above: 720
      - condition: numeric_state
        entity_id: 'sensor.weerstation_temperatuur_lastupdate'
        above: 30
  action:
    service: notify.slack
    data_template:
      message: >
        Een van de Mqtt services is down. Laatste updates: 
        Co2 woonkamer: {{ states.sensor.co2_woonkamer_lastupdate.state }}, 
        Co2 slaapkamer: {{ states.sensor.co2_slaapkamer_lastupdate.state }}, 
        Co2 studeerkamer: {{ states.sensor.co2_studeerkamer_lastupdate.state }}, 
        Watermeter: {{ states.sensor.watermeter_lastupdate.state }},
        Ventilator: {{ states.sensor.ventilator_snelheid_lastupdate.state }},
        Weerstation: {{ states.sensor.weerstation_temperatuur_lastupdate.state }}.
      target: "@rob"

- id: kerst_aan
  alias: Kerstlampjes aan voor zonsondergang
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.kerst
    service: homeassistant.turn_on
- id: kerst_uit
  alias: Kerstlampjes uit om 22:00:00
  trigger:
  - at: '22:00:00'
    platform: time
  action:
  - data:
      entity_id: group.kerst
    service: homeassistant.turn_off
- id: ventilator_aan
  alias: Ventilator aan
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'fan.ventilatiesysteem'
        state: 'off'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: 'sensor.co2_slaapkamer'
            above: '600'
          - condition: numeric_state
            entity_id: 'sensor.co2_studeerkamer'
            above: '600'
          - condition: numeric_state
            entity_id: 'sensor.co2_woonkamer'
            above: '600'
  action:
    - service: fan.turn_on
      entity_id: fan.ventilatiesysteem
- id: ventilator_uit
  alias: Ventilator uit
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'fan.ventilatiesysteem'
        state: 'on'
      - condition: numeric_state
        entity_id: 'sensor.co2_slaapkamer'
        below: '600'
      - condition: numeric_state
        entity_id: 'sensor.co2_studeerkamer'
        below: '600'
      - condition: numeric_state
        entity_id: 'sensor.co2_woonkamer'
        below: '600'
  action:
    - service: fan.turn_off
      entity_id: fan.ventilatiesysteem
