- id: kerst_aan
  alias: Kerstlampjes aan voor zonsondergang
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.kerst
    service: homeassistant.turn_on
- id: kerst_uit
  alias: Kerstlampjes uit om 22:00:00
  trigger:
  - at: '22:00:00'
    platform: time
  action:
  - data:
      entity_id: group.kerst
    service: homeassistant.turn_off
