# Doe de lichten aan bij het openen van het slot als de lampen in het afgelopen uur niet aan- of uitgezet zijn
- id: licht_aan_bij_thuiskomst
  alias: Licht aan bij thuiskomst
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.deur
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: time
      before: '21:00'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.group.woonkamer_lights.last_changed)) > 3600  }}'
  action:
    service: homeassistant.turn_on
    entity_id: group.woonkamer_lights

- id: ikea_dimmer_waarde
  alias: Dimmer waarde
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/ikea_dimmer'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.ikea_lamp_1
        - light.ikea_lamp_2
        - light.ikea_lamp_3
    data_template:
      brightness: '{{ states.sensor["ikea_dimmer"].state | int }}'

- id: deur_op_slot
  alias: Deur op slot
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.deur
      from: 'off'
      to: 'on'
  action:
    service: notify.slack
    data_template:
      message: >
        Deur op slot
      target: "@rob"

- id: deur_van_slot
  alias: Deur van slot
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.deur
      from: 'on'
      to: 'off'
  action:
    service: notify.slack
    data_template:
      message: >
        Deur van slot
      target: "@rob"

- id: mqtt_channel_check
  alias: Mqtt channel check
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: 'sensor.co2_woonkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.co2_slaapkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.co2_studeerkamer_lastupdate'
        above: 30
      - condition: numeric_state
        entity_id: 'sensor.watermeter_lastupdate'
        above: 720
      - condition: numeric_state
        entity_id: 'sensor.ventilator_snelheid_lastupdate'
        above: 720
  action:
    service: notify.slack
    data_template:
      message: >
        Een van de Mqtt services is down. Laatste updates: 
        Co2 woonkamer: {{ states.sensor.co2_woonkamer_lastupdate.state }}, 
        Co2 slaapkamer: {{ states.sensor.co2_slaapkamer_lastupdate.state }}, 
        Co2 studeerkamer: {{ states.sensor.co2_studeerkamer_lastupdate.state }}, 
        Watermeter: {{ states.sensor.watermeter_lastupdate.state }},
        Ventilator: {{ states.sensor.ventilator_snelheid_lastupdate.state }},
        Weerstation: {{ states.sensor.weerstation_temperatuur_lastupdate.state }}.
      target: "@rob"

- id: ventilator_aan
  alias: Ventilator aan
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'fan.ventilatiesysteem'
        state: 'off'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: 'sensor.co2_slaapkamer'
            above: '600'
          - condition: numeric_state
            entity_id: 'sensor.co2_studeerkamer'
            above: '600'
          - condition: numeric_state
            entity_id: 'sensor.co2_woonkamer'
            above: '600'
  action:
    - service: fan.turn_on
      entity_id: fan.ventilatiesysteem

- id: ventilator_uit
  alias: Ventilator uit
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'fan.ventilatiesysteem'
        state: 'on'
      - condition: numeric_state
        entity_id: 'sensor.co2_slaapkamer'
        below: '600'
      - condition: numeric_state
        entity_id: 'sensor.co2_studeerkamer'
        below: '600'
      - condition: numeric_state
        entity_id: 'sensor.co2_woonkamer'
        below: '600'
  action:
    - service: fan.turn_off
      entity_id: fan.ventilatiesysteem
