- id: slaapkamer_wall_switch_click
  alias: Slaapkamer lamp toggle
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/slaapkamer_wall_switch
  condition:
    condition: template
    value_template: '{{ "single" == trigger.payload_json.click }}'
  action:
    service: light.toggle
    entity_id: light.slaapkamer_light
- id: slaapkamer_switch_toggle
  alias: Slaapkamer lamp toggle by cube shake
  trigger:
  - device_id: 1a392f4db3154ec698b0b45be60a43ce
    discovery_id: 0x00158d00029bf642 action_shake
    domain: mqtt
    platform: device
    subtype: shake
    type: action
  condition: []
  action:
  - entity_id: light.slaapkamer_light
    service: light.toggle
- id: slaapkamer_switch_dim_lower
  alias: Slaapkamer lamp dim lower by cube
  trigger:
  - device_id: 1a392f4db3154ec698b0b45be60a43ce
    discovery_id: 0x00158d00029bf642 action_rotate_left
    domain: mqtt
    platform: device
    subtype: rotate_left
    type: action
  condition: []
  action:
  - data_template:
      brightness: '{{ states.light.slaapkamer_light.attributes.brightness | int -
        25 | int }}'
    entity_id: light.slaapkamer_light
    service: light.turn_on
- id: slaapkamer_switch_dim_up
  alias: Slaapkamer lamp dim up by cube
  trigger:
  - device_id: 1a392f4db3154ec698b0b45be60a43ce
    discovery_id: 0x00158d00029bf642 action_rotate_right
    domain: mqtt
    platform: device
    subtype: rotate_right
    type: action
  condition: []
  action:
  - data_template:
      brightness: '{{ states.light.slaapkamer_light.attributes.brightness | int +
        25 | int }}'
    entity_id: light.slaapkamer_light
    service: light.turn_on
- id: slaapkamer_switch_default_color
  alias: Slaapkamer lamp default kleur by cube 180 flip
  trigger:
  - device_id: 1a392f4db3154ec698b0b45be60a43ce
    discovery_id: 0x00158d00029bf642 action_flip180
    domain: mqtt
    platform: device
    subtype: flip180
    type: action
  condition:
  - condition: template
    value_template: '{{ states.light.slaapkamer_light.attributes.rgb_color != (255,198,118)}}'
  action:
  - data:
      rgb_color:
      - 255
      - 200
      - 118
    entity_id: light.slaapkamer_light
    service: light.turn_on
- id: slaapkamer_switch_red
  alias: Slaapkamer lamp maak rood by cube 180 flip
  trigger:
  - device_id: 1a392f4db3154ec698b0b45be60a43ce
    discovery_id: 0x00158d00029bf642 action_flip180
    domain: mqtt
    platform: device
    subtype: flip180
    type: action
  condition:
  - condition: template
    value_template: '{{ "flip180" == trigger.payload_json.action }}'
  action:
  - data:
      rgb_color:
      - 255
      - 38
      - 38
    entity_id: light.slaapkamer_light
    service: light.turn_on
- id: cube_dim_lower
  alias: Ikea trio dim lower by cube
  trigger:
  - device_id: 6e69e7e532be4926a98017418b028a18
    discovery_id: 0x00158d000278f1dc action_rotate_left
    domain: mqtt
    platform: device
    subtype: rotate_left
    type: action
  condition: []
  action:
  - device_id: 3be62dd9f8e246b1a9a2ba0759bfd820
    domain: light
    entity_id: light.ikea_lamp_1_light
    type: brightness_decrease
  - device_id: d9acf390484542b684e865060e74236c
    domain: light
    entity_id: light.ikea_lamp_2_light
    type: brightness_decrease
  - device_id: 32adab2b2ea849218b1b741a2b6b0c61
    domain: light
    entity_id: light.ikea_lamp_3_light
    type: brightness_decrease
- id: cube_dim_upper
  alias: Ikea trio dim up by cube
  trigger:
  - device_id: 6e69e7e532be4926a98017418b028a18
    discovery_id: 0x00158d000278f1dc action_rotate_right
    domain: mqtt
    platform: device
    subtype: rotate_right
    type: action
  condition: []
  action:
  - device_id: 3be62dd9f8e246b1a9a2ba0759bfd820
    domain: light
    entity_id: light.ikea_lamp_1_light
    type: brightness_increase
  - device_id: d9acf390484542b684e865060e74236c
    domain: light
    entity_id: light.ikea_lamp_2_light
    type: brightness_increase
  - device_id: 32adab2b2ea849218b1b741a2b6b0c61
    domain: light
    entity_id: light.ikea_lamp_3_light
    type: brightness_increase
- id: toggle_woonkamer_lights
  alias: Toggle woonkamer lights by cube shake
  trigger:
  - device_id: 6e69e7e532be4926a98017418b028a18
    discovery_id: 0x00158d000278f1dc action_shake
    domain: mqtt
    platform: device
    subtype: shake
    type: action
  condition: []
  action:
  - entity_id: group.woonkamer_lights
    service: homeassistant.toggle
- id: enable_zigbee_join
  alias: Enable Zigbee joining
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- id: licht_aan_bij_thuiskomst
  alias: Licht aan bij thuiskomst
  trigger:
  - platform: state
    entity_id: binary_sensor.deur
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: time
      before: '21:00'
    - condition: template
      value_template: '{{ (as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d,
        %H:%M")) - as_timestamp(states.group.woonkamer_lights.last_changed)) > 3600
        }}'
  action:
    service: homeassistant.turn_on
    entity_id: group.woonkamer_lights
- id: ikea_dimmer_waarde
  alias: Ikea trio dimmer
  trigger:
  - device_id: c25c9143943c4b9fb1b53430ce30efc1
    discovery_id: 0x000b57fffe902bb0 action_rotate_stop
    domain: mqtt
    platform: device
    subtype: rotate_stop
    type: action
  condition: []
  action:
  - data:
      entity_id:
      - light.ikea_trio
    data_template:
      brightness: '{{ states("sensor.ikea_dimmer_brightness") | int }}'
    service: light.turn_on
- id: deur_op_slot
  alias: Deur op slot
  trigger:
  - platform: state
    entity_id: binary_sensor.deur
    from: 'off'
    to: 'on'
  action:
    service: notify.slack
    data_template:
      message: 'Deur op slot

        '
      target: '#deur'
- id: deur_van_slot
  alias: Deur van slot
  trigger:
  - platform: state
    entity_id: binary_sensor.deur
    from: 'on'
    to: 'off'
  action:
    service: notify.slack
    data_template:
      message: 'Deur van slot

        '
      target: '#deur'
- id: mqtt_channel_check
  alias: Mqtt channel check
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.co2_woonkamer_lastupdate
      above: 30
    - condition: numeric_state
      entity_id: sensor.co2_slaapkamer_lastupdate
      above: 30
    - condition: numeric_state
      entity_id: sensor.co2_studeerkamer_lastupdate
      above: 30
    - condition: numeric_state
      entity_id: sensor.ventilator_snelheid_lastupdate
      above: 720
    - condition: numeric_state
      entity_id: sensor.weerstation_temperatuur_lastupdate
      above: 720
  action:
    service: notify.slack
    data_template:
      message: 'Een van de Mqtt services is down. Laatste updates:  Co2 woonkamer:
        {{ states.sensor.co2_woonkamer_lastupdate.state }},  Co2 slaapkamer: {{ states.sensor.co2_slaapkamer_lastupdate.state
        }},  Co2 studeerkamer: {{ states.sensor.co2_studeerkamer_lastupdate.state
        }},  Watermeter: {{ states.sensor.watermeter_lastupdate.state }}, Ventilator:
        {{ states.sensor.ventilator_snelheid_lastupdate.state }}, Weerstation: {{
        states.sensor.weerstation_temperatuur_lastupdate.state }}.

        '
      target: '#general'
- id: ventilator_aan
  alias: Ventilator aan
  trigger:
    platform: time_pattern
    minutes: /10
    seconds: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: fan.ventilatiesysteem
      state: 'off'
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.slaapkamer_mh_z19_co2_waarde
        above: '600'
      - condition: numeric_state
        entity_id: sensor.studeerkamer_mh_z19_co2_waarde
        above: '600'
      - condition: numeric_state
        entity_id: sensor.woonkamer_mh_z19_co2_waarde
        above: '600'
  action:
  - service: fan.turn_on
    entity_id: fan.ventilatiesysteem
- id: ventilator_uit
  alias: Ventilator uit
  trigger:
    platform: time_pattern
    minutes: /10
    seconds: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: fan.ventilatiesysteem
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.slaapkamer_mh_z19_co2_waarde
      below: '600'
    - condition: numeric_state
      entity_id: sensor.studeerkamer_mh_z19_co2_waarde
      below: '600'
    - condition: numeric_state
      entity_id: sensor.woonkamer_mh_z19_co2_waarde
      below: '600'
  action:
  - service: fan.turn_off
    entity_id: fan.ventilatiesysteem
- id: '1584283441188'
  alias: Light to message
  description: ''
  trigger:
  - device_id: f3ea00de61fc471fb2a1b362a9c540b7
    discovery_id: 0x00158d0002cb71ef click_single
    domain: mqtt
    platform: device
    subtype: single
    type: click
  condition: []
  action:
  - data_template:
      message: 'Slaapkamer switch

        '
      target: '#upgrading-our-lamps'
    service: notify.slack
