# Weather prediction
#  - platform: yr

- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/co2_sensor/PPM'
  name: 'Co2 slaapkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Humidity'
  name: 'Luchtvochtigheid slaapkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Temperature'
  name: 'Temperatuur slaapkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Pressure'
  name: 'Luchtdruk slaapkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/esp_easy_woonkamer/co2_sensor/PPM'
  name: 'Co2 woonkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Humidity'
  name: 'Luchtvochtigheid woonkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Temperature'
  name: 'Temperatuur woonkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Pressure'
  name: 'Luchtdruk woonkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/co2_sensor/PPM'
  name: 'Co2 studeerkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Humidity'
  name: 'Luchtvochtigheid studeerkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Temperature'
  name: 'Temperatuur studeerkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Pressure'
  name: 'Luchtdruk studeerkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/watermeter/flow/Count'
  name: 'Watermeter flow'
  unit_of_measurement: 'liter'

- platform: mqtt
  state_topic: '/weatherstation/Temp'
  name: 'Temperatuur weerstation'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/weatherstation/Pressure'
  name: 'Luchtdruk weerstation'
  unit_of_measurement: 'hPa'
- platform: mqtt
  state_topic: '/weatherstation/Humidity'
  name: 'Luchtvochtigheid weerstation'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/weatherstation/Lux'
  name: 'Lux weerstation'
  unit_of_measurement: 'lux'

- platform: miflora
  mac: 'C4:7C:8D:64:3B:41'
  name: Dracaena marginata
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
#- platform: miflora
#  mac: 'C4:7C:8D:64:45:97'
#  name: Picea abies
#  force_update: false
#  median: 3
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery

- platform: template
  sensors:
    huiskamer_hum:
      friendly_name: "Luchtvochtigheid huiskamer"
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.sensebender_micro_1_2.state | int - 10 }}"

- platform: template
  sensors:
    huiskamer:
      value_template: '{{ states.remote.huiskamer.attributes.current_activity }}'

- platform: mqtt
  name: Ventilator tijd
  state_topic: "/ventilator/itho/Timer"
  value_template: "{{value}}"
  unit_of_measurement: 's'
- platform: mqtt
  name : Ventilator snelheid
  state_topic: "/ventilator/itho/State"
  value_template: >
    {% if value|float==0 %}Standby{% endif %}
    {% if value|float==1 %}Laag{% endif %}
    {% if value|float==2 %}Medium{% endif %}
    {% if value|float==3 %}Hoog{% endif %}
    {% if value|float==4 %}Full{% endif %}
    {% if value|float>=11 %}Hoog(T){% endif %}
