# Weather prediction
#  - platform: yr

#- platform: mqtt
#  state_topic: 'location/owner/presence/b4:f1:da:64:75:66'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Rob woonkamer'
#- platform: mqtt
#  state_topic: 'location/owner/presence/ac:37:43:77:b3:a2'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Svanhild woonkamer'

- platform: mqtt
  state_topic: 'mysensors-out/169/2/1/0/1'
  name: 'Weerhuis luchtvochtigheid'
  unit_of_mesurement: '%'
- platform: mqtt
  state_topic: 'mysensors-out/169/3/1/0/0'
  name: 'Weerhuis temperatuur'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: 'mysensors-out/169/4/1/0/23'
  name: 'Weerhuis lux'
  unit_of_measurement: 'lux'

- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/co2_sensor/PPM'
  name: 'Co2 slaapkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Humidity'
  name: 'Luchtvochtigheid slaapkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Temperature'
  name: 'Temperatuur slaapkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_slaapkamer/bme280/Pressure'
  name: 'Luchtdruk slaapkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/esp_easy_woonkamer/co2_sensor/PPM'
  name: 'Co2 woonkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Humidity'
  name: 'Luchtvochtigheid woonkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Temperature'
  name: 'Temperatuur woonkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_woonkamer/bme280/Pressure'
  name: 'Luchtdruk woonkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/co2_sensor/PPM'
  name: 'Co2 studeerkamer'
  unit_of_measurement: 'ppm'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Humidity'
  name: 'Luchtvochtigheid studeerkamer'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Temperature'
  name: 'Temperatuur studeerkamer'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: '/esp_easy_studeerkamer/bme280/Pressure'
  name: 'Luchtdruk studeerkamer'
  unit_of_measurement: 'hPa'

- platform: mqtt
  state_topic: '/watermeter/flow/Count'
  name: 'Watermeter flow'
  unit_of_measurement: 'liter'

- platform: miflora
  mac: 'C4:7C:8D:64:3B:41'
  name: Dracaena marginata
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
#- platform: miflora
#  mac: 'C4:7C:8D:64:45:97'
#  name: Picea abies
#  force_update: false
#  median: 3
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery

#- platform: template
#  sensors:
#    dummy_sensor:
#      friendly_name: 'Dummy sensor voor actions'
#      unit_of_measurement: '%'
#      value_template: '{{ 1 }}'
      

- platform: template
  sensors:
    huiskamer_hum:
      friendly_name: "Luchtvochtigheid huiskamer"
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.sensebender_micro_1_2.state | int - 10 }}"

- platform: template
  sensors:
    huiskamer:
      value_template: '{{ states.remote.huiskamer.attributes.current_activity }}'

- platform: mqtt
  name: Ventilator tijd
  state_topic: "/ventilator/itho/Timer"
  value_template: "{{value}}"
  unit_of_measurement: 's'
- platform: mqtt
  name : Ventilator snelheid
  state_topic: "/ventilator/itho/State"
  value_template: >
    {% if value|float==0 %}Standby{% endif %}
    {% if value|float==1 %}Laag{% endif %}
    {% if value|float==2 %}Medium{% endif %}
    {% if value|float==3 %}Hoog{% endif %}
    {% if value|float==4 %}Full{% endif %}
    {% if value|float>=11 %}Hoog(T){% endif %}
  force_update: true

- platform: time_date
  display_options:
    - 'date_time'

# force time update: https://community.home-assistant.io/t/template-sensor-not-updating/60965/2

- platform: template
  sensors:
    co2_woonkamer_lastupdate:
      friendly_name: Co2 sensor woonkamer last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.co2_woonkamer.last_updated))/60)|round|int -119}}'
    co2_slaapkamer_lastupdate:
      friendly_name: Co2 sensor slaapkamer last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.co2_slaapkamer.last_updated))/60)|round|int -119 }}'
    co2_studeerkamer_lastupdate:
      friendly_name: Co2 sensor studeerkamer last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.co2_studeerkamer.last_updated))/60)|round|int -119 }}'
    watermeter_lastupdate:
      friendly_name: Watermeter last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.watermeter_flow.last_updated))/60)|round|int -119 }}'
    ventilator_snelheid_lastupdate:
      friendly_name: Ventilator snelheid last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.ventilator_snelheid.last_updated))/60)|round|int -119 }}'
    weerhuis_temperatuur_lastupdate:
      friendly_name: Weerhuis temperatuur last updated
      unit_of_measurement: 'min'
      value_template: '{{ ((as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.weerhuis_temperatuur.last_updated))/60)|round|int -119 }}'

